version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp
      MYSQL_PASSWORD: MyApp@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm run migrate && npm run seed && npm run dev"

volumes:
  mysql_data:
